production:
  recycle_candidates_job:
    class: MidnightJob
    schedule: every weekday at 12:00am

  remind_update_calendars_job:
    class: RemindUpdateCalendarJob
    schedule: at 10am every monday
